### ISSUE TITLE
problem with RLE24 compressed images

### ISSUE THREAD

**Issue by lpgb** [th-otto/zview#1]
There's a bug in the RLE24 decoder. A 'repeating group' shouldn't be padded. Finally found a sample file. The following lines should be removed:
if (status_byte & 1)
{
	Fread(handle, 1, &input);
}

[rle24rletrns.bmp.zip](https://github.com/th-otto/zview/files/3687471/rle24rletrns.bmp.zip)

**Comment by th-otto** [comment]
Thanks, should be fixed now.

**Comment by th-otto** [comment]
Thanks, should be fixed now.
